apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homebridge
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homebridge
  syncPolicy: {}
  source:
    repoURL: https://github.com/etatsu/k3s-at-home.git
    targetRevision: HEAD
    path: ootb-apps/homebridge
    plugin:
      name: argocd-lovely-plugin
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homebridge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true