apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deployments-manager-app
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: deployments-manager
  source:
    path: deployments/
    repoURL: https://github.com/etatsu/k3s-at-home.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: deployments-manager
  namespace: argo-cd
spec:
  description: App-of-Apps Manager
  sourceRepos:
    - https://github.com/etatsu/k3s-at-home.git
  destinations:
    - namespace: argo-cd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
