apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deployments-manager-app
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: deployments-manager
  source:
    path: deployments/
    repoURL: https://github.com/etatsu/k3s-at-home.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
