argo-cd:
  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 1

  dex:
    enabled: false # No need for dex in homelab

  server:
    autoscaling: 
      enabled: true
      minReplicas: 1
    extraArgs:
      - --insecure # No need for TLS in homelab
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
