argo-cd:
  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 1
    extraContainers: # Add argocd-lovely-plugin
      - name: lovely-plugin
        command: [/var/run/argocd/argocd-cmp-server]
        image: ghcr.io/crumbhole/argocd-lovely-plugin-cmp:0.19.6
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp-dir
    volumes:
      - name: tmp-dir
        emptyDir: {}

  dex:
    enabled: false # No need for dex in homelab

  server:
    service:
      type: NodePort
    autoscaling: 
      enabled: true
      minReplicas: 1
    extraArgs:
      - --insecure # No need for TLS in homelab
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
